FROM ubuntu:14.04

# Install Python
RUN apt-get install -y python python build-essential pkg-config

# Do following install tasks in /tmp
WORKDIR /tmp

# Install latest pip
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python2.7 get-pip.py

# Add a user (creating home and specifying shell) and
# use it when running the container
RUN useradd --create-home --shell /bin/bash docker
USER docker
WORKDIR /home/docker

# Add a Stencila storage directory
RUN mkdir -p /home/docker/store
ENV STORES /home/docker/store